apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-config
  labels:
    app: {{ .Values.appName }}
    environment: {{ .Values.environment }}
    team: {{ .Values.team }}
    version: {{ .Values.version }}
    {{- with .Values.customLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    # This checksum ensures the ConfigMap is updated when labels change
    checksum/labels: {{ printf "%s-%s-%s-%s-%s" .Values.appName .Values.environment .Values.team .Values.version (toJson .Values.customLabels) | sha256sum }}
data:
  app.name: {{ .Values.appName | quote }}
  environment: {{ .Values.environment | quote }}
  team: {{ .Values.team | quote }}
  message: "Hello from {{ .Values.appName }} in {{ .Values.environment }} environment!"
